"""update teacher model

Revision ID: 225edf64221a
Revises: 81a72093ad9c
Create Date: 2025-01-31 16:03:42.280337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '225edf64221a'
down_revision: Union[str, None] = '81a72093ad9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_faculties_id', table_name='faculties')
    op.drop_index('ix_faculties_name', table_name='faculties')
    op.drop_table('faculties')
    op.drop_index('ix_departments_id', table_name='departments')
    op.drop_index('ix_departments_name', table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('faculty_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculties.id'], name='departments_faculty_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='departments_pkey')
    )
    op.create_index('ix_departments_name', 'departments', ['name'], unique=True)
    op.create_index('ix_departments_id', 'departments', ['id'], unique=False)
    op.create_table('faculties',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='faculties_pkey')
    )
    op.create_index('ix_faculties_name', 'faculties', ['name'], unique=True)
    op.create_index('ix_faculties_id', 'faculties', ['id'], unique=False)
    # ### end Alembic commands ###
