"""update teacher model

Revision ID: a715a910a5fa
Revises: ea607d2e840b
Create Date: 2025-01-31 15:34:27.272510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a715a910a5fa'
down_revision: Union[str, None] = 'ea607d2e840b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers', sa.Column('last_name', sa.String(), nullable=False))
    op.add_column('teachers', sa.Column('first_name', sa.String(), nullable=False))
    op.add_column('teachers', sa.Column('contact', sa.String(), nullable=False))
    op.add_column('teachers', sa.Column('science_teacher', sa.String(), nullable=False))
    op.drop_column('teachers', 'username')
    op.drop_column('teachers', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('teachers', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('teachers', 'science_teacher')
    op.drop_column('teachers', 'contact')
    op.drop_column('teachers', 'first_name')
    op.drop_column('teachers', 'last_name')
    # ### end Alembic commands ###
