"""Change student model 

Revision ID: d9a07b65da02
Revises: 1c21708f754a
Create Date: 2025-01-28 15:20:43.332552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9a07b65da02'
down_revision: Union[str, None] = '1c21708f754a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('students', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('students', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
