"""adds user model

Revision ID: e811bf5ba3d9
Revises: 3e8a6c91b81f
Create Date: 2025-01-29 16:13:48.673434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e811bf5ba3d9'
down_revision: Union[str, None] = '3e8a6c91b81f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
