"""Changed tasks table

Revision ID: 7e0ff8002ba4
Revises: b52096460987
Create Date: 2025-01-24 16:49:57.515663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e0ff8002ba4'
down_revision: Union[str, None] = 'b52096460987'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answers')
    op.add_column('questions', sa.Column('A', sa.String(), nullable=False))
    op.add_column('questions', sa.Column('B', sa.String(), nullable=False))
    op.add_column('questions', sa.Column('C', sa.String(), nullable=False))
    op.add_column('questions', sa.Column('D', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'D')
    op.drop_column('questions', 'C')
    op.drop_column('questions', 'B')
    op.drop_column('questions', 'A')
    op.create_table('answers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_correct', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name='answers_question_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='answers_pkey')
    )
    # ### end Alembic commands ###
