"""Add is_correct

Revision ID: f7cf7c551079
Revises: 9b253436e855
Create Date: 2025-01-27 14:02:54.994226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7cf7c551079'
down_revision: Union[str, None] = '9b253436e855'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'is_correct',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'is_correct',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
